config/routes.rb
Rails.application.routes.draw do


root to: 'homes#top'
get 'search' => 'posts#search'

get "about" => "homes#about" , as: "about"
   devise_for :users,
    controllers: { registrations: 'registrations' }

get :signup, to: 'users#new'


  resources :users
  resources :relationships, only: [:create, :destroy, :index]
  resources :ranks, only: [:index,:show,:new,:create,:destroy]
  resources :posts, only: [:index,:show,:new,:create,:destroy] do
   resources :likes, only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
   # collection do
   #    get :search
   # end
  end


  resources :notifications, only: :index




end

app/models/post.rb
class Post < ApplicationRecord

 belongs_to :user
 attachment :post_image
 belongs_to :contributer, class_name:'User', foreign_key: 'user_id'
 has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
 has_many :comments, dependent: :destroy
 has_many :notifications, dependent: :destroy

 validates :title, length: {maximum: 15}
 scope :search_caption_for, ->(query) { where('caption like ?', "%#{query}%") }



  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end


    def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
    end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end


def self.search(keyword)
  where("title LIKE ? OR caption LIKE ?", "%#{keyword}%", "%#{keyword}%")
end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!

  def index
    @posts = Post.limit(10).order('created_at DESC')
    @post = Post.new
  end

  def search
    @posts = Post.search(params[:keyword])
    @keyword = params[:keyword]
    # render :index
  end

  def new
     @post = Post.new
  end

  def create
    @post=current_user.posts.build(post_params)
    # =以下2文を含む
    # @post = Post.new(post_params)
    # @post.user_id = current_user.id
    if @post.save

      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { redirect_to root_path }
      end
    else
        respond_to do |format|
        format.html { render 'posts/_new' }
        format.js
        end
    end
  end

 def show
    @post=Post.find(params[:id])
 end



  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:info]="投稿を取り消しました"
    redirect_to posts_path
  end
  


  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :post_image, :caption, :user_id,)
    end



  def user_params
    params.require(:user).permit(:name, :self_introduction, :profile_image)
  end


    def correct_user

      post=Post.find(params[:id])
      contributer=post.contributer
      unless current_user==contributer
        session[:danger] = "このページにはアクセスできません"
        redirect_to root_url
      end
    end




end

app/helpers/posts_helper.rb
module PostsHelper
  HASHTAG_REGEX = /(?<=\s|　|^)#.+?(?=(　|\s|$))/.freeze

  def link_to_hashtag(caption)
    caption.gsub(HASHTAG_REGEX) { |hashtag| link_to(hashtag, search_posts_path(q: hashtag)) }
  end

  def html_with_link_to_hashtag(caption)
    # 下の処理でaタグのhref属性を表示できるようにするので、ハッシュタグのaタグ以外が有効にならないように、エスケープしておく。
    html_escaped_caption = h(caption)
    caption_with_hashtags = link_to_hashtag(html_escaped_caption)
    # aタグのhref属性以外はサニタイズします。
    # aタグのhref属性はエスケープされずに表示されるようになります。
    sanitize caption_with_hashtags, tags: ['a'], attributes: ['href']
  end

end

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "×", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>

    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_icon.html.erb
<% if post.liked_by(current_user).present? %>
    <%= link_to post_like_path(post.id, post.liked_by(current_user)), method: :delete, remote: true do %>
        <i class="fas fa-heart"></i>
    <% end %>
<% else %>
    <%= link_to post_likes_path(post), method: :post, remote: true do %>
        <i class="far fa-heart" ></i>
    <% end %>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/index.html.erb
<script src="https://kit.fontawesome.com/fcd80f662a.js" crossorigin="anonymous"></script>
<% @posts.each do |post| %>
  <div class="col-md-6 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header">
            <div class="row">
               <div class="col-md-6">
         <%= link_to user_path(post.user), class: "no-text-decoration" do %>
             <% if post.user.profile_image.url.nil? %>
                 <%= image_tag 'default_profile_img.png', class: "avatar avatar-size48" %>
             <% else %>
                 <%= image_tag post.user.profile_image.url, class: "avatar avatar-size48" %>
             <% end %>
         <% end %>
             <%= link_to user_path(post.user), class: "black-color no-text-decoration",title: post.user.name do %>
              <strong><%= post.user.name %></strong>
                   <% end %>
              </div>
               
               <div class="col-md-6 text-right">
                   <%= link_to(post_path(post)) do %>
                        <strong><%= post.title %></strong>
                   <% end %>
               </div>
               
               
           </div>
           
        </div>
        <div class="center"></br>
         <%= link_to(post_path(post)) do %>
          <%=attachment_image_tag post, :post_image , size:'300x300' %>
         <% end %>
        </div>
        <div class="card-body">
          <div class="row parts">
            <%# ==========いいねここから========== %>
            <div id="like-icon-post-<%= post.id.to_s %>">
             <%= render "like_icon", { post: post } %>
            </div>
            <%# ==========いいねここまで========== %>
           <%= link_to "", "#", class: "comment" %>
          </div>
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>
          <div>
           <%= html_with_link_to_hashtag(post.caption) %>
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
              class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
                <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-5 col-lg-8 col-md-10 col-sm-11 post-card">
   <div class="card-wrap">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">

            <div class="col pl-0">
              <%= f.text_field :title,  class: 'form-control' ,placeholder: "タイトル", rows: "3" %>
              <%= f.text_area :caption, class: "form-control border-0", placeholder: "アイデアを投稿", rows: "3" %>

            </div>
          </div>
          <div class="mb-3">

           <%= f.attachment_field :post_image%>

          </div>

          <%= f.submit "投稿する", class: "btn btn-primary btn-block"%>
        <% end %>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/posts/rank.html.erb
<% @all_ranks.each do |post| %>

  <div class="col-md-6 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header">
            <div class="row">
               <div class="col-md-6">
                   第<%= i %>位
         <%= link_to user_path(post.user), class: "no-text-decoration" do %>
             <% if post.user.profile_image.url.nil? %>
                 <%= image_tag 'default_profile_img.png', class: "avatar avatar-size48" %>
             <% else %>
                 <%= image_tag post.user.profile_image.url, class: "avatar avatar-size48" %>
             <% end %>
         <% end %>
             <%= link_to user_path(post.user), class: "black-color no-text-decoration",title: post.user.name do %>
              <strong><%= post.user.name %></strong>
                   <% end %>
              </div>
               
               <div class="col-md-6 text-right">
                   <%= link_to(post_path(post)) do %>
                        <strong><%= post.title %></strong>
                   <% end %>
               </div>
               
               
           </div>
           
        </div>
        <div class="center"></br>
         <%= link_to(post_path(post)) do %>
          <%=attachment_image_tag post, :post_image , size:'300x300' %>
         <% end %>
        </div>
        <div class="card-body">
          <div class="row parts">
            <%# ==========いいねここから========== %>
            <div id="like-icon-post-<%= @post.id.to_s %>">
             <% if @post.liked_by(current_user).present? %>
              <%= link_to post_like_path(@post.id, @post.liked_by(current_user)), method: :delete, remote: true do %>
              <i class="fas fa-heart"></i>
              <% end %>
               <% else %>
               <%= link_to post_likes_path(@post), method: :post, remote: true do %>
               <i class="far fa-heart" ></i>
              <% end %>
             <% end %>
            </div>
            <%# ==========いいねここまで========== %>
           <%= link_to "", "#", class: "comment" %>
          </div>
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>
          <div>
           <%= html_with_link_to_hashtag(post.caption) %>
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
              class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
                <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

<% end %>

app/views/posts/search.html.erb
  <div class="col-md-8 col-md-2 mx-auto">
        
    <form method="get" action="<%= search_path %>" class="search_container">
        <input type="text" name="keyword" size="25" placeholder="キーワード検索">
        <input type="submit" value="&#xf002">
    </form>
    
    </div>

              
              
              

<% @posts.each do |post| %>
  <div class="col-md-6 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header">
            <div class="row">
               <div class="col-md-6">
         <%= link_to user_path(post.user), class: "no-text-decoration" do %>
             <% if post.user.profile_image.url.nil? %>
                 <%= image_tag 'default_profile_img.png', class: "avatar avatar-size48" %>
             <% else %>
                 <%= image_tag post.user.profile_image.url, class: "avatar avatar-size48" %>
             <% end %>
         <% end %>
             <%= link_to user_path(post.user), class: "black-color no-text-decoration",title: post.user.name do %>
              <strong><%= post.user.name %></strong>
                   <% end %>
              </div>
               
               <div class="col-md-6 text-right", class: "no-text-decoration">
                   <!--%= link_to(post_path(post)) do %>-->
                   <%= link_to(post_path(post)) do %>
                        <strong><%= post.title %></strong>
                   <% end %>
               </div>
               
               
           </div>
           
        </div>
        <div class="center"></br>
         <%= link_to(post_path(post)) do %>
          <%=attachment_image_tag post, :post_image , size:'300x300' %>
         <% end %>
        </div>
        <div class="card-body">
          <div class="row parts">
            <%# ==========いいねここから========== %>
            <div id="like-icon-post-<%= post.id.to_s %>">
             <%= render "like_icon", { post: post } %>
            </div>
            <%# ==========いいねここまで========== %>
           <%= link_to "", "#", class: "comment" %>
          </div>
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>
          <div>
           <%= html_with_link_to_hashtag(post.caption) %>
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
              class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
                <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
  <div class="col-md-6 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header">
            <div class="row">
               <div class="col-md-6">
         <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
             <% if @post.user.profile_image.url.nil? %>
                 <%= image_tag 'default_profile_img.png', class: "avatar avatar-size48" %>
             <% else %>
                 <%= image_tag @post.user.profile_image.url, class: "avatar avatar-size48" %>
             <% end %>
         <% end %>
             <%= link_to user_path(@post.user), class: "black-color no-text-decoration",title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
                   <% end %>
               </div>
               
               <div class="col-md-6 text-right">
                   <%= link_to(post_path(@post)) do %>
                        <strong><%= @post.title %></strong>
                   <% end %>
               </div>
           </div>
           
        </div>
        <div class="center"></br>
         <%= link_to(post_path(@post)) do %>
          <%=attachment_image_tag @post, :post_image , size:'300x300' %>
         <% end %>
        </div>
        <div class="card-body">
          <div class="row parts">
            <%# ==========いいねここから========== %>
            <div id="like-icon-post-<%= @post.id.to_s %>">
             <% if @post.liked_by(current_user).present? %>
              <%= link_to post_like_path(@post.id, @post.liked_by(current_user)), method: :delete, remote: true do %>
              <i class="fas fa-heart"></i>
              <% end %>
               <% else %>
               <%= link_to post_likes_path(@post), method: :post, remote: true do %>
               <i class="far fa-heart" ></i>
              <% end %>
             <% end %>
            </div>
            <%# ==========いいねここまで========== %>
            <%= link_to "", "#", class: "comment" %>
          </div>
          <div id="like-text-post-<%= @post.id.to_s %>">
            <%= render "like_text", { likes: @post.likes } %>
          </div>
          <div>
           <%= html_with_link_to_hashtag(@post.caption) %>
           <div id="comment-post-<%= @post.id.to_s %>">
            <% @post.comments.each do |comment| %>
            <div class="mb-2">
             <% if comment.user == current_user %>
              <%= link_to "×", post_comment_path(@post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
             <% end %>
             <span>
              <strong>
               <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
              </strong>
             </span>
             <span><%= comment.comment %></span>
            </div>
            <% end %>
           </div>
           <%= link_to time_ago_in_words(@post.created_at).upcase + "前", post_path(@post),
            class: "light-color post-time no-text-decoration" %>
            <div class="container delete-post">
             <% if current_user==@post.contributer %>
             <hr>
             <%= link_to '投稿を取り消す', @post, method: :delete, data:{confirm: "本当に取り消しますか"}, class:"btn btn-danger btn-block" %>
             <% end %>
            </div>
            <hr>
            <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
              <%= form_with model: [@post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: @post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
                <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>