config/routes.rb
Rails.application.routes.draw do


root to: 'homes#top'
get 'search' => 'posts#search'

get "about" => "homes#about" , as: "about"
   devise_for :users,
    controllers: { registrations: 'registrations' }

get :signup, to: 'users#new'


  resources :users
  resources :relationships, only: [:create, :destroy, :index]
  resources :ranks, only: [:index,:show,:new,:create,:destroy]
  resources :posts, only: [:index,:show,:new,:create,:destroy] do
   resources :likes, only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
   # collection do
   #    get :search
   # end
  end


  resources :notifications, only: :index




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script src="https://kit.fontawesome.com/fcd80f662a.js" crossorigin="anonymous"></script>
<html>
  <head>
    <title>Kurashino_wa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- koko demo OK !! -->
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/posts"><%= image_tag 'Kurashino_wa.jpeg', :size => '250x100' %></a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-md-auto align-items-center">
            <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            
            <li class="nav-item">
             <a class="fas fa-crown fa-2x" href="/ranks">
             </a>
            </li>
            
            <li class="nav-item">
            <a class="far fa-bell fa-2x" href="/notifications"></a>
            </li>
            
            <a class="far fa-edit fa-2x" href="/posts/new"></a>
            
            
            
            <li class="nav-item">
              <%= link_to "新規投稿", new_post_path, class: "btn btn-primary tweet-btn" %>
            </li>
            <!--検索フォーム-->
            <li class="nav-item">
              <div class="input-group">
             <%#= form_with url: search_path, method: :get, class: "search_container", local: true do |f| %>
             <%#= f.text_field :keyword, value: @keyword, class: 'form-control' ,placeholder: "記事を検索" %>
              <!--<span class="input-group-btn">-->
              <!--  <button id="sbtn4" type="submit"><i class="fas fa-search"></i></button>-->
              <!--</span>-->
              <%#= f.button 'submit' %>
             <%# end %>
             <form method="get" action="<%= search_path %>" class="search_container">
                <input type="text" name="keyword" size="25" placeholder="キーワード検索">
                <input type="submit" value="&#xf002">
              </form>
              </div>
            </li>

            <% else %>
            <!--<li class="nav-item">-->
            <!--  %= link_to "about", about_path, class: 'nav-link text-dark' %>-->
            <!--</li>-->
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>


            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>

    <footer class="bg-dark text-white pt-5 pb-4">
    </footer>
    <!-- koko ni script -->
  </body>
</html>